### ISSUE TITLE
SandBox, CustomBattle, StoryMode missing in e1.8.0.321460

### ISSUE THREAD

**Issue by welles** [BUTR/Bannerlord.ReferenceAssemblies#43]
Hi there, there seems to be an issue in the newest beta version of the reference assemblies where the packages for SandBox, CustomBattle, and StoryMode are missing. Could you take a look at that?
Cheers!

**Comment by Aragas** [comment]
This is really weird. It's not our fault. It seems that the .dlls are missing from SandBox, StoryMode and CustomBattle> I'm not quire sure how this happen, but [SteamDb](https://steamdb.info/depot/261551/) seems to show this too, try `Modules/StoryMode` in the search filter.
Also, https://steamdb.info/patchnotes/9332085/, even the patchnotes indicate this, check `Modules/StoryMode/bin/Win64_Shipping_Client/StoryMode.GauntletUI.dll`

**Comment by welles** [comment]
Huh, that really is weird, and nobody seems to be talking about it. Maybe the classes I'm missing have moved to some other module... I'll have to try a clean install of the beta too, I'm pretty sure I saw these modules in the list when I was testing it. I guess this can be closed then, since it's not a problem with the reference assemblies. 😅

**Comment by Aragas** [comment]
This is most likely on TW's end.
If they moved the assemblies, all mods would be broken, and TW seems to respect most of the times breaking changes, this would be most likely an 1.9.x update category.
I contacted the devs, they confirmed this and a fix should be coming soon

**Comment by Aragas** [comment]
Well, they insist that the issue is fixed, but it's not. I'm hiding the latest package

**Comment by welles** [comment]
Hm... I guess we'll just have to wait on the next version then?
Thanks for looking into this!

**Comment by welles** [comment]
I found out that some of the modules have moved to [another depot](https://steamdb.info/depot/261552/). When I downloaded this depot in addition to the content depot in my build action it worked again. Could this be the fix the devs were talking about?

**Comment by Aragas** [comment]
Yep. Can't believe I missed that when I was checking the steamdb. It should work now, thanks for the info!
