### ISSUE TITLE
Including non-public members in reference assemblies

### ISSUE THREAD

**Issue by XT-0xFF** [BUTR/Bannerlord.ReferenceAssemblies#50]
Would it be possible for you to include non-public members of the assemblies in the reference assemblies?

When trying to use [Krafs.Publicizer](https://github.com/krafs/Publicizer) to access private members of the Bannerlord assemblies without the use of reflection I ran into the problem that these are not included in the reference assemblies. 
Normally the Publicizer makes it possible to publicize assemblies, thereby removing the need for reflection when using non-public members. As they are not included in the references though, the publication cannot work.

The author of Publicizer describes the issue and how it could be solve here:
https://github.com/krafs/Publicizer/issues/53#issuecomment-1304181975

**Comment by Aragas** [comment]
Hi! Sorry for the long answer, lost the issue!
This is a legality limitation. We have the full rights to extract a public API from assemblies, but the implementation details (private\internal) are copyrighted, so we can't provide reference assemblies that will contain those details. Even if we only keep private fields/properties/method signatures without the actual body.

I have currently no idea how to mitigate that. We do have tools that can download specific .dlls via Steam for any version that the game devs store as branches, but they will drop the branches soon.
So one of the possibilities would be to download them when the project is setup, but MSBuild does not provide a reliable way to do that

**Comment by XT-0xFF** [comment]
I was afraid that it might have been done this way due to legal issues, not that I see any logical reasons as to how including non-public members/methods (without code, of course) would be problematic - but I am not a lawyer, my knowledge of such legal topics is very limited!
I fully understand that you must adhere to copyright laws.

Sad to hear though, it would have been helpful to have them included, but even without it, Reflection gives access when needed and including the local dlls from the game itself allows for using the Publicizer, in case one really wishes to avoid Reflection - just a bit inconvenient if anyone else wishes to work on the project.

**Comment by Aragas** [comment]
This one of the reasons we use reflection with caching and delegate compilation.
While Publicizer doesn't introduce reflection overhead, you can only target one game version this way.
With reflection, you can target multiple game versions. If a type was moved or a variable renamed, it can be fixed by checking member existence dynamically!

**Comment by Aragas** [comment]
Closing for now, as there's nothing we can do, at least officially
