### ISSUE TITLE
Scheduled workflow disabled

### ISSUE THREAD

**Issue by FlorianV85** [BUTR/Bannerlord.ReferenceAssemblies#80]
Hello, the workflow seems to have been disabled automatically by github. Which I think is preventing updates, especially for uploading the v1.1.6 depot.

`This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days. Enable this workflow to resume scheduled runs. `
https://github.com/BUTR/Bannerlord.ReferenceAssemblies/actions/workflows/Generate%20References.yml

**Comment by Aragas** [comment]
Thanks for noticing! Enabled the workflow, will also manually trigger it

**Comment by FlorianV85** [comment]
Thank you!
